apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app : {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }} 
    spec:
      containers:
        - name : {{ .Release.Name }}-wp
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 80

---
#Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: optiblog-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2dev
    kind: Deployment
    name: optiblog-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70